### ISSUE TITLE
The file will load perfectly fine, however, once i enter my username in it crashes without doing anything?

### ISSUE THREAD

**Issue by jeffbuilder** [RishiTiku/InstagramJSONToReadableText#11]

**Comment by RishiTiku** [comment]
How did you enter your username? Please elaborate.

**Comment by jeffbuilder** [comment]
![Screenshot (103)](https://user-images.githubusercontent.com/58865034/70922075-79d90080-1ff3-11ea-82c9-1b4369bc0110.png)
![Screenshot (104)](https://user-images.githubusercontent.com/58865034/70922076-7a719700-1ff3-11ea-9c4e-5bd08cab266b.png)

As you can see, I have my messages.json file in the folder, I run the test.py and then when i enter my username, it fails.

**Comment by RishiTiku** [comment]
Hey man, You might be on Python 2.x or maybe a more recent version of python. Maybe 4.x if I am correct. Try this. Go to python website, download one of their releases like 3.6 (the program itself is coded in this) and run the program using IDLE (python's default IDE). It should work this time. Python version incompatibility is a common issue. Use it on Python 3.x only and it won't crash. Have a nice time

**Comment by RishiTiku** [comment]
Try running it using IDLE. If it doesn't help then try running the previous build of this script. This script wasn't coded by me. It was an addition. Try this one.
[Here](https://github.com/RishiTiku/InstagramJSONToReadableText/tree/ad92521fa83afbfe155152d7d8aa8e1f8c74fae2)

**Comment by jeffbuilder** [comment]
I ran it using idle, thank you so much.
