### ISSUE TITLE
Group messages per sender

### ISSUE THREAD

**Issue by tri-nga** [RishiTiku/InstagramJSONToReadableText#12]
Hi, thank you for this script, very helpful.
I would like to ask: How could I edit the script, so that in the resulting username.txt file, the format is something like this ? 

```
date, time - sender1: message
date, time - sender1: message

date, time - sender2: message

data, time - sender1: message
```
What I would like to achieve, is group messages per sender.

**Comment by RishiTiku** [comment]
Okay, I get it. You wish to have all chats of a single user in the entire dump sorted into one single file. I think it can be done by some changes, major and minor, but you'll have to wait for a week or so before I get free from my XII exams. Feel free to play around with the script if you are a coder. I'll try to post a new script by the next week. 
Welcome! ^ _ ^

**Comment by tri-nga** [comment]
Sorry I did explain it badly, my bad.
I'm ok with separate txt file, a file for each person.
Let's say Bob, the user parsing his message, had a conversation with Alice.

When he run your script againt his messages.json, he will get those conversation nicely separated.
He will have a file, Alice.txt too.

Inside this file, the conversation betweem Bob and Alice will be formatted like this (more or less)
```
Bob: This is a message from Bob,
BoB: this is another message from Bob
Alice: Alice answer to bob
Bob: Bob message alice again
Alice: Alice start blaming Bob
Alice: Alice won't stop soon
Alice: Alice going to kill Bob..
Bob: Bob do not know what's going on  XD
```

I would like the conversation to be formatted like this instead
```
Bob: This is a message from Bob,
BoB: this is another message from Bob
--- empty space / new line ---
Alice: Alice answer to bob
--- empty space / new line ---
Bob: Bob message alice again
--- empty space / new line ---
Alice: Alice start blaming Bob
Alice: Alice won't stop soon
Alice: Alice going to kill Bob..
--- empty space / new line ---
Bob: Bob do not know what's going on  XD
```

Is it possible ?

**Comment by RishiTiku** [comment]
Hey @dok42 ,
As per your request I've modified the code. Check it out in the Custom Builds folder.
