### ISSUE TITLE
Whenever i type in my instagram name, the program just crashes without anything happening.

### ISSUE THREAD

**Issue by orooney72** [RishiTiku/InstagramJSONToReadableText#13]
I cant make it past the part where it tells you to type in your instagram username, please help !

**Comment by RishiTiku** [comment]
What program are you running it on? Anyway download python IDLE 3.x from python.org and keep messages.json in the same folder as the script and then run the script. If you're running this script on Windows Default Command Prompt Python Interpreter, it's highly likely that it won't work. Try using IDLE and run the script on it.

**Comment by orooney72** [comment]
i downloaded the lastest version of python, i get to the black screen with the text and when i click enter it just closes

**Comment by orooney72** [comment]
how do i run the script on idle?

**Comment by RishiTiku** [comment]
Download IDLE. Open the script on it. Keep Messages.json in same folder as the script. Press F5. The black screen means that you were using Windows CMD only so it's okay!

**Comment by orooney72** [comment]
so idle is a seperate program? bc i saw a different discussion and they had the same issue and you said to use idle so i searched idle in my files and tried that but i had no idea wha i was doing :/

**Comment by RishiTiku** [comment]
Download it here
https://www.python.org/downloads/release/python-374/

**Comment by orooney72** [comment]
where do i click im lost, i kinda know nothing abt this kinda stuff

**Comment by orooney72** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/61398950/75128243-0a793000-5678-11ea-958d-ad6b001d3eb3.png)

**Comment by orooney72** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/61398950/75128273-24b30e00-5678-11ea-9d78-471b34f8444e.png)
![Screenshot (3)](https://user-images.githubusercontent.com/61398950/75128274-27156800-5678-11ea-8aed-52a0b0738d09.png)

**Comment by orooney72** [comment]
is this how its supposed to look?

**Comment by RishiTiku** [comment]
Create a folder on desktop called **Messages**. 
Paste **messages.json** in the **Messages** folder. Take it from your **downloaded Instagram dump**.
Paste **test.py** from the **downloaded InstagramJSONToReadableText master** package in the **Messages** folder.
Now your **Messages** folder should have **test.py** and **messages.json**.
Right click on **test.py** and click **Open with Python IDLE** or something along the same lines from the drop-down menu. Or you can open IDLE application first, click **File => Open** and then **navigate to desktop** and open **test.py** from **Messages** folder.
Once test.py is opened in IDLE, **press F5 or click run script**. (It should be present in one of the menus.)
Follow the directions on-screen. You'll find a new folder inside **Messages** folder. Open it and you'll have all the chats sorted by their usernames on Instagram.

Phew. You can thank me now. Maybe upvote and give me a star. This step is optional but still mandatory.

**Comment by orooney72** [comment]
ok that made it work, thanks i had no clue what i was doing lol, i still got the messages and it works well

**Comment by RishiTiku** [comment]
Hell yeah! Happy to help!😂

**Comment by mclaudw** [comment]
> Create a folder on desktop called **Messages**.
> Paste **messages.json** in the **Messages** folder. Take it from your **downloaded Instagram dump**.
> Paste **test.py** from the **downloaded InstagramJSONToReadableText master** package in the **Messages** folder.
> Now your **Messages** folder should have **test.py** and **messages.json**.
> Right click on **test.py** and click **Open with Python IDLE** or something along the same lines from the drop-down menu. Or you can open IDLE application first, click **File => Open** and then **navigate to desktop** and open **test.py** from **Messages** folder.
> Once test.py is opened in IDLE, **press F5 or click run script**. (It should be present in one of the menus.)
> Follow the directions on-screen. You'll find a new folder inside **Messages** folder. Open it and you'll have all the chats sorted by their usernames on Instagram.
> 
> Phew. You can thank me now. Maybe upvote and give me a star. This step is optional but still mandatory.

I tried what you said but its giving me an error:
=============== RESTART: C:\Users\ana\Desktop\Messages\test.py ===============
Enter Your Instagram Username here!!! Please enter correctly.
 >>>analithgow
Traceback (most recent call last):
  File "C:\Users\ana\Desktop\Messages\test.py", line 173, in <module>
    f = open(os.path.join(username, "Group{}.txt".format(ctr)),"w", encoding='utf-8-sig')
FileNotFoundError: [Errno 2] No such file or directory: 'analithgow\\Group1.txt'
>>>

**Comment by RishiTiku** [comment]
I'll definitely look into it. It's probably because of a bug in the new build. Try a previous build and see if that works for you.
 https://github.com/RishiTiku/InstagramJSONToReadableText/tree/60154549a4f4c3d48d3e6e9a7227565e84e19d7e

Try this one. This new build has something to do with the group folder. I'll fix it soon.

**Comment by RishiTiku** [comment]
I've modified the code again. This time it should work like a charm. Lemme know if it does or if it doesn't, Try downloading the newest build.

**Comment by mclaudw** [comment]
Traceback (most recent call last):
  File "C:\Users\ana\Downloads\InstagramJSONToReadableText-master\test.py", line 183, in <module>
    f = open(os.path.join(username, "Group{}.txt".format(ctr)),"w", encoding='utf-8-sig')
FileNotFoundError: [Errno 2] No such file or directory: 'analithgow\\Group1.txt'

**Comment by RishiTiku** [comment]
This issue is internal. The computer isn't creating a directory called analithgow. Therefore the file named Group 1 which should exist inside analithgow cannot be created. Thus the error.
 
I am not sure if it might work, but try creating a directory yourself bearing your Instagram ID name where test.py is located and rerun the program.

Create a directory called analithgow in the same folder as test.py and messages.json and run test.py. I'll post some patch code shortly afterwards.

**Comment by RishiTiku** [comment]
Done! The Error has been rectified! Happy to help!

Thanks for the Bug report BTW.
Love from India.

**Comment by mclaudw** [comment]
Yes, it worked! Thanks
