### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Harsh4300** [RishiTiku/InstagramJSONToReadableText#14]
Hi! So when I try to run this it shows an error and i dont know what to do.
![Annotation 2020-03-01 034811](https://user-images.githubusercontent.com/61637001/75615929-2f860b00-5b70-11ea-908d-081a7519ad9a.png)

**Comment by RishiTiku** [comment]
Have you copied the messages.json in the same folder as test.py?

**Comment by Harsh4300** [comment]
Yeah i have. I had clicked on the always open with notepad option before while opening the file. Would that have done something?

**Comment by RishiTiku** [comment]
https://github.com/RishiTiku/InstagramJSONToReadableText/tree/9f10798024e5dfa35373a208acb310190078b60c
Try downloading this commit or just go through issue #13 Follow steps there.

**Comment by RishiTiku** [comment]
Hey @Harsh4300 ,
I've modified the code again. Seems like this one's gonna work. Try the newest Build.
