### ISSUE TITLE
Time Stamp Issue

### ISSUE THREAD

**Issue by bubbaTX95** [RishiTiku/InstagramJSONToReadableText#15]
test.py sometimes gets the wrong time stamp conversion.
See attached picture

![TimeError](https://user-images.githubusercontent.com/62249757/76767992-68290580-6768-11ea-8d9d-641a8227d2e0.png)

**Comment by RishiTiku** [comment]
Hi, 
Looks like a bug definitely. Can I know what time was that supposed to be actually? And what timezone did you input in it?

**Comment by bubbaTX95** [comment]
Thanks for replying

Time zone was Central Time Zone in United States. So entry into the program was "-05" for hours and "00" for minutes.

Times before this entry were converted correctly. Only about 10 time entries in the whole file were incorrect.

See attached pictures.

Checked time conversion at http://coderstoolbox.net/unixtimestamp/
  2017-07-20T00:24:45.875102+00 -->  Wed, 19 Jul 2017 19:24:45 -05:00

So the correct time is 19:24:45  or 7:24:45 PM CST. But the converted text program shows "0-5:24:45AM"
The minutes & seconds are correct but the hours are wrong and the "AM" is wrong"


-----Original Message-----

**Comment by RishiTiku** [comment]
Yeah sure. I recently added the custom time stamp feature and Boy Did the old programming not cope with it! No issues. I'm just having my exams right now, so I'm busy a bit. I'll try to see what's wrong and definitely post a solution anytime soon. Stay tuned.

And yeah, Welcome! All your love makes my day wonderful. Love from India. 🇮🇳

**Comment by RishiTiku** [comment]
Hello There!
Based on your observation, I have rectified the program. If you have the time, test it and post me the result. Thanks again for the bug report!!! 💯

**Comment by bubbaTX95** [comment]
Tested the new version and it works. The bug has been fixed.
Thanks


-----Original Message-----
