### ISSUE TITLE
Wrong username? 

### ISSUE THREAD

**Issue by voolys** [RishiTiku/InstagramJSONToReadableText#2]
I put in my username correctly but the code is saying its the incorrect username. 
![image](https://user-images.githubusercontent.com/52866985/61175970-4b5b8300-a586-11e9-85e1-b8d7bc1c787e.png)

EDIT: the username is correct but now its stated as "not defined"

**Comment by suvikp** [comment]
I get the same error too, it exports like 4 txt files (all group conversations) then i get the error saying wrong username.

**Comment by RishiTiku** [comment]
Thanks for notifying. The Problem has been rectified. Now you can enter your username directly from the command line. Just Run the program and it'll do.
HappyToHelp
`username = str(input('Enter Your Instagram Username here!!! Please enter correctly.\n >>>')) #gets your Instagram username here in string format`
P.S. It  was just a minor Fix but I am just a kid anyway! :))))

**Comment by suvikp** [comment]
It works perfectly! Thanks man, much appreciated it. Also is there any way to link the images with the text?

**Comment by RishiTiku** [comment]
Working on that right now. Maybe next build... :)))))

**Comment by RishiTiku** [comment]
> I put in my username correctly but the code is saying its the incorrect username.
> ![image](https://user-images.githubusercontent.com/52866985/61175970-4b5b8300-a586-11e9-85e1-b8d7bc1c787e.png)
> 
> EDIT: the username is correct but now its stated as "not defined"

@voolys
Try running the code again without modifying anything. its expected to work this time.
HappyToHelp
`username = str(input('Enter Your Instagram Username here!!! Please enter correctly.\n >>>')) #gets your Instagram username here in string format
#username = 'rishi.tiku' #My username, if you wish to, replace your username here, remove the '#' in front and put a '#' in front of previous line.`
if you see a problem again, try decommenting the second line and comment the first. Replace your username too.
eg
`#username = str(input('Enter Your Instagram Username here!!! Please enter correctly.\n >>>')) #gets your Instagram username here in string format
username = 'kinqwu' #YOUR username(I guess!), if you wish to, replace your username here, remove the '#' in front and put a '#' in front of previous line.`
**Put all dots, underscores, etc correctly and it should work like a charm.**


>

**Comment by suvikp** [comment]
Waiting patiently for the next build then :) do you have an ETA?
