### ISSUE TITLE
Is There A Way To Generate Text Files Without The Times?

### ISSUE THREAD

**Issue by NaphanB** [RishiTiku/InstagramJSONToReadableText#4]
I love how  easy to use this program is to use and how readable the files are once they have been converted by your code :) but I was also wondering if I could make the files easier to read by removing the times the messages were sent. Is this possible to do?

**Comment by RishiTiku** [comment]
@Naphan0 Yes, sure it is. The code takes the data from the dump, modifies it and then puts it into human readable format. In the first part, it strips off the time and date from the data and puts it into your file. In the second, it takes the name, followed by the message. The new file created (containing readable text) is nothing but a result of formatting done by the program. So yes, it is possible. If you are a python coder yourself, using an IDE for python or even a text editor like notepad, you can find all the lines where it is written `f.write(time)` immediately followed by `f.write(" - ")` **(for your convenience, lines 136, 137, 172, 173, 204, 205)** and put a `#` just before them, preferably without whitespaces or lines in between the `#` and the lines mentioned. Your new code may look like `#f.write(time)` and `#f.write(" , ")` at the specified lines.
This is essentially called commenting, meaning that the code is written as a comment, and will be ignored during execution. This should successfully ignore the part of code which is responsible for adding the time to your files. An intriguing request, to be honest, definitely strange, but this code is only meant for you all. Use Notepad or any IDE for formatting.
Thank you for your compliments. Such things make someone's day. You can support me by giving me a star. You may also follow me for more useful content.
Thank you! :)
