### ISSUE TITLE
Showing only one month in a large conversation

### ISSUE THREAD

**Issue by poison6** [RishiTiku/InstagramJSONToReadableText#8]
Hello! First of all Great work! very useful program! I have one issue, i have a very large conversation and it only shows one month (it reaches ~205kb if it helps), I dont have this issue with other smaller conversations. Is there anything i can change to fix this? thank you

**Comment by RishiTiku** [comment]
@poison6 Thank you! The problem you say has never been experienced by me. (I've used Instagram too for around 4 years!) The code is supposed to work regardless of the file size. Also, to be honest, I've generated files >1Mb. Try opening messages.json using WordPad, and maybe search for chats belonging to the same conversation. Do you see some chats that are present there but not outputted by the program? Or your dump only contained 1 month of data? If answer to former is true, you can try to copy paste all those chats (in json format) manually to another file, make sure json syntax is correct, rename the new file as messages.json, and run test.py on the new file. This should create a new text file containing the chats you require. Keep the newly created messages.json in a new folder as the names may clash. Also you may send screenshots for help in development, to make next builds better or you can send the messages.json file @ sunilrobin786@gmail.com for a custom solution. I promise you all privacy.
Thank you once again. 😊
