### ISSUE TITLE
Bug when you have a group of only 2 people and have another open conversation between them

### ISSUE THREAD

**Issue by matheusantunesnandi** [RishiTiku/InstagramJSONToReadableText#9]
Possui um bug que confundia um grupo de até 2 pessoas com uma conversa normal entre elas. 
Este grupo possuia as mesmas pessoas que integariam em outra conversa normal existente.
A cada loop é sobrescrito o arquivo de texto gerado anteriormente. 

Dessa forma que alterei, se já houver um arquivo existente gerado anteriormente, mesmo que confunda, ela será salvo semelhantemente, mas com um número incrementado ao lado.

Exemplo:
A conversa normal entre Fulana e Beltrana vai para um arquivo beltrana.txt

O grupo com apenas Fulana e Beltrana vai para um arquivo beltrana2.txt

**Insira o código abaixo antes do primeiro
             _f = open(os.path.join(username, "{}.txt".format(p[value])), 'w', encoding = 'utf-8-sig')_**

```
            path = './' + username + '/' + "{}.txt".format(p[value])
            filerepeatedcount = 2


            if (os.path.exists(path)):
                path = './' + username + '/' + p[value] + str(filerepeatedcount) + '.txt'

                while (os.path.exists(path)):
                    filerepeatedcount += 1
                    path = './' + username + '/' + p[value] + str(filerepeatedcount) + '.txt'

                p[value] = p[value] + str(filerepeatedcount)
```

**Comment by RishiTiku** [comment]
Yes correct! It's a bug. Thank you for reporting. I didn't know if there was a way to differentiate between a group chat and a normal 1-1 chat. Thank you so much. I shall try to work around it for a solution!!

**Comment by RishiTiku** [comment]
Your idea is quite appreciable. I'll integrate it. You deserve contribution credits for that too. Happy friendship from India. 🇮🇳

**Comment by RishiTiku** [comment]
Sim, correto! É um bug. Obrigado por denunciar. Não sabia se havia uma maneira de diferenciar entre um bate-papo em grupo e um bate-papo 1-1 normal. Muito obrigado. Vou tentar contornar isso para uma solução!
Sua ideia é bastante apreciável. Eu vou integrá-lo. Você merece créditos de contribuição por isso também. Feliz amizade da Índia. 🇮🇳

**Comment by matheusantunesnandi** [comment]
Fico bastante contente em ler isto!
Feliz amizade do Brasil! ^^

**Comment by RishiTiku** [comment]
Hey @matheusantunesnandi ,
The code that you merged had a flaw inside, many people got errors after using it. I've used your insight to create a better code without errors. Thanks again for the bug report.

**Comment by matheusantunesnandi** [comment]
Hello again!
Ow right. If you have identified the error and corrected that, great!

That was my first code on python and first time that I contribute on github rsrsrs


Happy for contribute with your vision, tight hug!
